version: "3"

services:

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - backend
    restart: unless-stopped

  mongodb:
    image: mongo
    networks:
      - backend
    volumes:
      - mongodbdata:/data/db
    restart: unless-stopped

networks:
  backend:

volumes:
  mongodbdata:


