GET http://localhost:8000/v1/order?id=63341930b88a177efcf2ef5e
Content-Type: application/json

{}

###

POST http://localhost:8000/v1/order
Content-Type: application/json

{
    "order_status": "ACCEPTED",
    "customer_id": "321321321"
}

###

PUT http://localhost:8000/v1/order
Content-Type: application/json

{
    "id": "633167c053f16e46fd4ebd14",
    "order_status": "APPROVED",
    "customer_id": "321321"
}

###

DELETE http://localhost:8000/v1/order?id=633167c053f16e46fd4ebd14
Content-Type: application/json

{}

###