basePath: /v1
consumes:
    - application/json
info:
    description: Documentation for Orders API
    version: 1.0.0
paths:
    /v1/order:
        get:
            consumes:
                - application/json
            description: |-
                This will show all available pets by default.
                You can get the pets that are out of stock
            operationId: order
            parameters:
                - description: id
                  in: query
                  name: id
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    $ref: '#/responses/success'
                "400":
                    $ref: '#/responses/bad'
                    description: parameters
                "404":
                    $ref: '#/responses/order'
                    description: not found
                "500":
                    $ref: '#/responses/server'
                    description: error
            schemes:
                - http
            summary: Lists pets filtered by some parameters.
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
