GET http://localhost:8000/v1/order?id=634e4edfcc9acce23cddb0ff
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjYxMTk0NTgsImlhdCI6MTY2NjA3NjI1OCwidXNlcl9pZCI6IjYzNGQ3OTA0OWIxZWIxNWQwZjk4ZTU2YiJ9.BPzUHd5ZXO4UGMkch80C0bcPmvb_HuiII1ob_uMmc-A

{}

###

POST http://localhost:8000/v1/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjYxMTk0NTgsImlhdCI6MTY2NjA3NjI1OCwidXNlcl9pZCI6IjYzNGQ3OTA0OWIxZWIxNWQwZjk4ZTU2YiJ9.BPzUHd5ZXO4UGMkch80C0bcPmvb_HuiII1ob_uMmc-A

{
    "order_status": "ACCEPTED",
    "customer_id": "test docker compose"
}

###

PUT http://localhost:8000/v1/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjYxMTk0NTgsImlhdCI6MTY2NjA3NjI1OCwidXNlcl9pZCI6IjYzNGQ3OTA0OWIxZWIxNWQwZjk4ZTU2YiJ9.BPzUHd5ZXO4UGMkch80C0bcPmvb_HuiII1ob_uMmc-A

{
    "id": "634ac85d5de5b1c46d862201",
    "order_status": "APPROVED",
    "customer_id": "test update gin"
}

###

DELETE http://localhost:8000/v1/order?id=634ac85d5de5b1c46d862201
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjYxMTk0NTgsImlhdCI6MTY2NjA3NjI1OCwidXNlcl9pZCI6IjYzNGQ3OTA0OWIxZWIxNWQwZjk4ZTU2YiJ9.BPzUHd5ZXO4UGMkch80C0bcPmvb_HuiII1ob_uMmc-A

{}

###

POST http://localhost:8000/auth/signUp
Content-Type: application/json

{
    "firstname": "firstname",
    "lastname": "lastname",
    "username": "username",
    "password": "password"
}

###

POST http://localhost:8000/auth/signIn
Content-Type: application/json

{
    "username": "username",
    "password": "password"
}

###
