GET http://localhost:8000/v1/order?id=634d158a9b147262289ec6d0
Content-Type: application/json

{}

###

POST http://localhost:8000/v1/order
Content-Type: application/json

{
    "order_status": "ACCEPTED",
    "customer_id": "test docker compose"
}

###

PUT http://localhost:8000/v1/order
Content-Type: application/json

{
    "id": "634ac85d5de5b1c46d862201",
    "order_status": "APPROVED",
    "customer_id": "test update gin"
}

###

DELETE http://localhost:8000/v1/order?id=634ac85d5de5b1c46d862201
Content-Type: application/json

{}

###
